/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface ToasterPoolInterface extends utils.Interface {
  functions: {
    "_1inch()": FunctionFragment;
    "approveMax(address,address)": FunctionFragment;
    "balances(address,address)": FunctionFragment;
    "decreaseLiqduidity(address,uint128)": FunctionFragment;
    "fee()": FunctionFragment;
    "fillOrderPostInteraction(bytes32,address,address,uint256,uint256,uint256,bytes)": FunctionFragment;
    "increaseLiquidity(address,uint256,uint256)": FunctionFragment;
    "init(int24,int24,uint256,uint256)": FunctionFragment;
    "isInRange()": FunctionFragment;
    "lock()": FunctionFragment;
    "locked()": FunctionFragment;
    "owner()": FunctionFragment;
    "period()": FunctionFragment;
    "pool()": FunctionFragment;
    "positionManager()": FunctionFragment;
    "rebalance(int24,int24)": FunctionFragment;
    "reinvest()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setPeriod(uint24)": FunctionFragment;
    "state()": FunctionFragment;
    "strategy()": FunctionFragment;
    "tickSpacing()": FunctionFragment;
    "token0()": FunctionFragment;
    "token1()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "uniswapV3SwapCallback(int256,int256,bytes)": FunctionFragment;
    "userShare(address)": FunctionFragment;
    "zapCalculator()": FunctionFragment;
    "zapLiquidity(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_1inch"
      | "approveMax"
      | "balances"
      | "decreaseLiqduidity"
      | "fee"
      | "fillOrderPostInteraction"
      | "increaseLiquidity"
      | "init"
      | "isInRange"
      | "lock"
      | "locked"
      | "owner"
      | "period"
      | "pool"
      | "positionManager"
      | "rebalance"
      | "reinvest"
      | "renounceOwnership"
      | "setPeriod"
      | "state"
      | "strategy"
      | "tickSpacing"
      | "token0"
      | "token1"
      | "transferOwnership"
      | "uniswapV3SwapCallback"
      | "userShare"
      | "zapCalculator"
      | "zapLiquidity"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "_1inch", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveMax",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseLiqduidity",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fillOrderPostInteraction",
    values: [
      BytesLike,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseLiquidity",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isInRange", values?: undefined): string;
  encodeFunctionData(functionFragment: "lock", values?: undefined): string;
  encodeFunctionData(functionFragment: "locked", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "period", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rebalance",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "reinvest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(functionFragment: "strategy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tickSpacing",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3SwapCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "userShare", values: [string]): string;
  encodeFunctionData(
    functionFragment: "zapCalculator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "zapLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "_1inch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approveMax", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseLiqduidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fillOrderPostInteraction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isInRange", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "period", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reinvest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPeriod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "strategy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tickSpacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3SwapCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userShare", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zapCalculator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zapLiquidity",
    data: BytesLike
  ): Result;

  events: {
    "DecreaseLiquidity(address,uint256,uint256)": EventFragment;
    "IncreaseLiquidity(address,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DecreaseLiquidity"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IncreaseLiquidity"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface DecreaseLiquidityEventObject {
  user: string;
  decreasedAmount0: BigNumber;
  decreasedAmount1: BigNumber;
}
export type DecreaseLiquidityEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  DecreaseLiquidityEventObject
>;

export type DecreaseLiquidityEventFilter =
  TypedEventFilter<DecreaseLiquidityEvent>;

export interface IncreaseLiquidityEventObject {
  user: string;
  investedAmount0: BigNumber;
  investedAmount1: BigNumber;
}
export type IncreaseLiquidityEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  IncreaseLiquidityEventObject
>;

export type IncreaseLiquidityEventFilter =
  TypedEventFilter<IncreaseLiquidityEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ToasterPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ToasterPoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _1inch(overrides?: CallOverrides): Promise<[string]>;

    approveMax(
      token: string,
      spender: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    decreaseLiqduidity(
      user: string,
      decreasedShare: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    fee(overrides?: CallOverrides): Promise<[number]>;

    fillOrderPostInteraction(
      arg0: BytesLike,
      maker: string,
      arg2: string,
      arg3: BigNumberish,
      takingAmount: BigNumberish,
      remainingAmount: BigNumberish,
      interactionData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    increaseLiquidity(
      user: string,
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    init(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isInRange(
      overrides?: CallOverrides
    ): Promise<[boolean] & { inRange: boolean }>;

    lock(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    locked(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    period(overrides?: CallOverrides): Promise<[BigNumber]>;

    pool(overrides?: CallOverrides): Promise<[string]>;

    positionManager(overrides?: CallOverrides): Promise<[string]>;

    rebalance(
      newTickLower: BigNumberish,
      newTickUpper: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    reinvest(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setPeriod(
      _period: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    state(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, BigNumber, BigNumber] & {
        tokenId: BigNumber;
        tickLower: number;
        tickUpper: number;
        liquidity: BigNumber;
        totalShare: BigNumber;
      }
    >;

    strategy(overrides?: CallOverrides): Promise<[string]>;

    tickSpacing(overrides?: CallOverrides): Promise<[number]>;

    token0(overrides?: CallOverrides): Promise<[string]>;

    token1(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    userShare(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    zapCalculator(overrides?: CallOverrides): Promise<[string]>;

    zapLiquidity(
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  _1inch(overrides?: CallOverrides): Promise<string>;

  approveMax(
    token: string,
    spender: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  balances(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  decreaseLiqduidity(
    user: string,
    decreasedShare: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  fee(overrides?: CallOverrides): Promise<number>;

  fillOrderPostInteraction(
    arg0: BytesLike,
    maker: string,
    arg2: string,
    arg3: BigNumberish,
    takingAmount: BigNumberish,
    remainingAmount: BigNumberish,
    interactionData: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  increaseLiquidity(
    user: string,
    amount0: BigNumberish,
    amount1: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  init(
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    amount0: BigNumberish,
    amount1: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isInRange(overrides?: CallOverrides): Promise<boolean>;

  lock(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  locked(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  period(overrides?: CallOverrides): Promise<BigNumber>;

  pool(overrides?: CallOverrides): Promise<string>;

  positionManager(overrides?: CallOverrides): Promise<string>;

  rebalance(
    newTickLower: BigNumberish,
    newTickUpper: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  reinvest(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setPeriod(
    _period: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  state(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, number, BigNumber, BigNumber] & {
      tokenId: BigNumber;
      tickLower: number;
      tickUpper: number;
      liquidity: BigNumber;
      totalShare: BigNumber;
    }
  >;

  strategy(overrides?: CallOverrides): Promise<string>;

  tickSpacing(overrides?: CallOverrides): Promise<number>;

  token0(overrides?: CallOverrides): Promise<string>;

  token1(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  uniswapV3SwapCallback(
    amount0Delta: BigNumberish,
    amount1Delta: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  userShare(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  zapCalculator(overrides?: CallOverrides): Promise<string>;

  zapLiquidity(
    amount0: BigNumberish,
    amount1: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    _1inch(overrides?: CallOverrides): Promise<string>;

    approveMax(
      token: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decreaseLiqduidity(
      user: string,
      decreasedShare: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    fee(overrides?: CallOverrides): Promise<number>;

    fillOrderPostInteraction(
      arg0: BytesLike,
      maker: string,
      arg2: string,
      arg3: BigNumberish,
      takingAmount: BigNumberish,
      remainingAmount: BigNumberish,
      interactionData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    increaseLiquidity(
      user: string,
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    init(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    isInRange(overrides?: CallOverrides): Promise<boolean>;

    lock(overrides?: CallOverrides): Promise<void>;

    locked(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    period(overrides?: CallOverrides): Promise<BigNumber>;

    pool(overrides?: CallOverrides): Promise<string>;

    positionManager(overrides?: CallOverrides): Promise<string>;

    rebalance(
      newTickLower: BigNumberish,
      newTickUpper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    reinvest(overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setPeriod(_period: BigNumberish, overrides?: CallOverrides): Promise<void>;

    state(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, BigNumber, BigNumber] & {
        tokenId: BigNumber;
        tickLower: number;
        tickUpper: number;
        liquidity: BigNumber;
        totalShare: BigNumber;
      }
    >;

    strategy(overrides?: CallOverrides): Promise<string>;

    tickSpacing(overrides?: CallOverrides): Promise<number>;

    token0(overrides?: CallOverrides): Promise<string>;

    token1(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    userShare(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    zapCalculator(overrides?: CallOverrides): Promise<string>;

    zapLiquidity(
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DecreaseLiquidity(address,uint256,uint256)"(
      user?: null,
      decreasedAmount0?: null,
      decreasedAmount1?: null
    ): DecreaseLiquidityEventFilter;
    DecreaseLiquidity(
      user?: null,
      decreasedAmount0?: null,
      decreasedAmount1?: null
    ): DecreaseLiquidityEventFilter;

    "IncreaseLiquidity(address,uint256,uint256)"(
      user?: null,
      investedAmount0?: null,
      investedAmount1?: null
    ): IncreaseLiquidityEventFilter;
    IncreaseLiquidity(
      user?: null,
      investedAmount0?: null,
      investedAmount1?: null
    ): IncreaseLiquidityEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    _1inch(overrides?: CallOverrides): Promise<BigNumber>;

    approveMax(
      token: string,
      spender: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decreaseLiqduidity(
      user: string,
      decreasedShare: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    fillOrderPostInteraction(
      arg0: BytesLike,
      maker: string,
      arg2: string,
      arg3: BigNumberish,
      takingAmount: BigNumberish,
      remainingAmount: BigNumberish,
      interactionData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    increaseLiquidity(
      user: string,
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    init(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isInRange(overrides?: CallOverrides): Promise<BigNumber>;

    lock(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    locked(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    period(overrides?: CallOverrides): Promise<BigNumber>;

    pool(overrides?: CallOverrides): Promise<BigNumber>;

    positionManager(overrides?: CallOverrides): Promise<BigNumber>;

    rebalance(
      newTickLower: BigNumberish,
      newTickUpper: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    reinvest(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setPeriod(
      _period: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    state(overrides?: CallOverrides): Promise<BigNumber>;

    strategy(overrides?: CallOverrides): Promise<BigNumber>;

    tickSpacing(overrides?: CallOverrides): Promise<BigNumber>;

    token0(overrides?: CallOverrides): Promise<BigNumber>;

    token1(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    userShare(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    zapCalculator(overrides?: CallOverrides): Promise<BigNumber>;

    zapLiquidity(
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _1inch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approveMax(
      token: string,
      spender: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    balances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decreaseLiqduidity(
      user: string,
      decreasedShare: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fillOrderPostInteraction(
      arg0: BytesLike,
      maker: string,
      arg2: string,
      arg3: BigNumberish,
      takingAmount: BigNumberish,
      remainingAmount: BigNumberish,
      interactionData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    increaseLiquidity(
      user: string,
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    init(
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isInRange(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lock(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    locked(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    period(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    positionManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rebalance(
      newTickLower: BigNumberish,
      newTickUpper: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    reinvest(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setPeriod(
      _period: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    state(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    strategy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tickSpacing(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    uniswapV3SwapCallback(
      amount0Delta: BigNumberish,
      amount1Delta: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    userShare(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    zapCalculator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    zapLiquidity(
      amount0: BigNumberish,
      amount1: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
